# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.define "healthithost", primary: true do |hithost|
		hithost.vm.box = "ubuntu/trusty64"
		hithost.vm.network :private_network, ip: "192.168.1.70"
		hithost.vm.hostname = "healthithost"
		hithost.vm.provision "docker"
		hithost.vm.network :forwarded_port, guest: 80, host: 8080
		hithost.vm.network :forwarded_port, guest: 3306, host: 13306
		hithost.vm.network :forwarded_port, guest: 2222, host: 2223
		hithost.vm.provider "virtualbox" do |v|
			v.name = "healthithost"
			v.memory = 2048
		end
	end
#	config.vm.provision "shell",
#	inline: "mkdir -p /home/ashishpagar/{.composer,.drush}"
end